#!/usr/bin/env bash

#http://www.davidpashley.com/articles/writing-robust-shell-scripts/
#set -o nounset
set -o errexit

quiet=$2;
PATH=~/bin:/user/local/bin:$PATH
build_dir=$(dirname $0)
cd $build_dir
is_missing=false
build_tools_dir=tools
if [ ! -e $build_tools_dir ]; then
    echo "build tools dir: $build_tools_dir does not exist"
    echo
    is_missing=true
fi
getdata=$build_tools_dir/read-data
if [ ! -e $getdata ]; then
    echo "read-data: $getdata does not exist"
    echo
    is_missing=true
fi
config_file=config.ini
if [ ! -e $config_file ]; then
    echo "config file: $config_file does not exist"
    echo
    is_missing=true
fi
distroot=$($getdata $config_file files dist)
if [ ! -e $distroot ]; then
    echo "dist root: $distroot does not exist"
    echo
    is_missing=true
fi
srcroot=$($getdata $config_file files src)
if [ ! -e $srcroot ]; then
    echo "src root: $srcroot does not exist"
    echo
    is_missing=true
fi
if ! type java >/dev/null 2>&1; then
    echo 'Java must be installed to run the closure compiler'
    is_missing=true
fi
COMPILER=$($getdata $config_file files js_compiler)
if [ ! -e "$COMPILER" ]; then
    echo "compiler: $COMPILER does not exist"
    echo 'Download from: http://dl.google.com/closure-compiler/compiler-latest.zip'
    is_missing=true
fi
if ! type /usr/local/bin/fixjsstyle >/dev/null 2>&1; then
    echo 'fixjsstyle is not installed'
    echo 'To install: sudo easy_install http://closure-linter.googlecode.com/files/closure_linter-latest.tar.gz'
    echo
    is_missing=true
fi
if ! type tidy >/dev/null 2>&1; then
    echo 'Tidy must be installed'
    echo
    is_missing=true
fi

if [[ $is_missing == 'true' ]]; then
    exit
fi

output_file=build.log
source $build_tools_dir/color_and_error.bash

COMPILE_VENDOR='false'
if [ "$2" == 'compile_vendor' ]; then
    COMPILE_VENDOR='true'
fi

title(){
    if [ "$quiet" == 'quiet' ]; then return; fi
    echo ''
    colorize "$1" $ulon$blueb
}
ok(){
    if [ "$quiet" == 'quiet' ]; then return; fi
    colorize "[ok]" $greenf nonl
    echo " $*"
}
err(){
    if [ "$quiet" == 'quiet' ]; then
        echo "[$1] $2"
    else
        colorize "[$1]" $redf$boldon nonl
        echo " $2"
    fi
    exit 1
}
get-files(){
    ini_files=$($build_tools_dir/read-data $config_file files $1)
    for f in $ini_files; do
        if [ ! -e $f ]; then
            echo "$f Does not exist."
            exit 1
        fi
    done

    echo $ini_files
}


# ----------------------------------------------------
# make sure all files listed in config.ini exist
verify(){
    for type in html js css images vendor_js vendor_js_externs \
                vendor_js_sourcemaps; do
        title $type
        for f in $($getdata $config_file files $type); do
            if [ ! -e $f ]; then
                colorize "[error]" $redf nonl
                colorize " $f" $redf
            else
                ok $f
            fi
        done
    done
}


# ----------------------------------------------------
dolint(){
    if [ "$quiet" == 'quiet' ]; then return; fi

    title 'Lint js_assets:'

    js_assets=$(get-files js) || error $js_assets
    for f in $js_assets; do
        out=$(fixjsstyle --strict $f);
        ok "$f  $out";
    done

    #for f in $js_assets; do
    #    # if gjslint --strict $f 2>&1 | tee --append $output_file; then
    #    if gjslint --strict $f; then
    #       ok $f
    #    else
    #       echo ''
    #       while true; do
    #           read -p "Lint error: Try to fix errors?  <y> to fix: " yn
    #           case $yn in
    #               [Yy]* )
    #                   fixjsstyle --strict $f;
    #                   break
    #                   ;;
    #               * )
    #                   exit
    #                   ;;
    #           esac
    #       done
    #       exit
    #    fi
    #done
}


# ----------------------------------------------------
# rebuild app dir structure

rebuild_dir(){
    title 'Build dist dir:'

    if ! rm -rf $distroot/*; then
        error "could not delete $distroot"
    fi
    ok "deleted: $distroot/*"

    for f in js css css/images images; do
        new=$distroot/$f
        if ! mkdir $new; then
            error "could not create dir: $new"
        fi
        ok "created dir: $new"
    done
}


# ----------------------------------------------------
compile_js(){
    title 'Compile app js:'

    js_assets=$(get-files js) || error $js_assets
    js="$distroot/js"
    js_name='main.js'

    cat $js_assets > $js/$js_name
    # if fast, only concatenate js, don't use closure compiler
    if [ "$1" == 'fast' ]; then
        ok "FAST COMPILE - $js/$js_name"
        return
    fi

    format=''
    if [ "$1" = 'pretty' ]; then
        format='--formatting PRINT_INPUT_DELIMITER --formatting PRETTY_PRINT'
    fi

    if [ "$1" = 'fastcompile' ]; then
        compilation_level='SIMPLE_OPTIMIZATIONS'
    else
        compilation_level='ADVANCED_OPTIMIZATIONS'
    fi

    source_domain='http://moviesource.localhost/js/'
    replace_string='\('
    # build [--js FILE ...etc.] list:
    for f in $js_assets; do
        # build command line for compiler source list
        source_list="$source_list --js $(basename $f)" # strip off the path

        # build sed regex to change the sources filenames in
        # main.js.map to use the source domain url
        replace_string="$replace_string$(basename $f)\|"
    done
    replace_string=$(echo $replace_string | sed 's/.$/)/')

    vendor_externs=$(get-files vendor_js_externs) || error $vendor_externs
    for f in $vendor_externs; do
        externs="$externs --externs $f"
    done

    # build needs to cd to the js dir to compile the js so the
    # sources list in the map file do not have any paths attached
    # to them
    if $(cd js; java -jar $COMPILER \
            --compilation_level $compilation_level \
            $format \
            $source_list \
            --create_source_map $js_name.map \
            $externs \
            --warning_level VERBOSE \
            --js_output_file $js_name)
    then
        if $(grep WARNING $output_file); then
            err $(cat $output_file)
        fi

        sed -i "s@$replace_string@$source_domain\1@g" js/$js_name.map

        if [ "$1" == "fake" ]; then
            rm js/$js_name js/$js_name.map
        else
            # write the source map string to the compiled js
            (echo; echo -n "//# sourceMappingURL=/js/$js_name.map") >> js/$js_name

            mv js/$js_name js/$js_name.map $js
            ok "$js/main.js"
        fi
    else
        err 'compile error' " $js/$js_name"
    fi
}


# ----------------------------------------------------
# compile or copy vendor libs

compile-or-copy_vendor(){
    vend_temp=vendor-UNCOMPILED.js
    vend_js=vendor.js
    vendor_libs=$(get-files vendor_js) || error $vendor_libs
    #vendor_extras="$(get-files vendor_js_sourcemaps) $(get-files vendor_js_externs)" \
    #              || error $vendor_extras
    vendor_extras=$(get-files vendor_js_externs) || error $vendor_extras

    if [ $COMPILE_VENDOR = 'true' ]; then
        title 'Compile vendor js:'
        cat $vendor_libs > $js/$vend_temp
            #--formatting PRETTY_PRINT \
        if java -jar $COMPILER \
                --compilation_level SIMPLE_OPTIMIZATIONS \
                --js $js/$vend_temp \
                --js_output_file $js/vend.js \
            1>$output_file 2>$output_file; then

            rm $js/$vend_temp
            ok " $js/vend_js"
        else
            err 'compile error' " $js/$vend_temp"
        fi
    else
        title 'Copy vendor js:'
        if cp $vendor_libs $vendor_extras $js; then
            for f in $vendor_libs; do
                ok "$(basename $f)";
            done
        else
            err 'copy vendor js failed'
        fi
    fi
}

# ----------------------------------------------------
# sass will compile all sass files in a dir so we don't
# need to specify each sass file in the config.ini, just
# the dir
compile_sass(){
    title 'Compile SASS:'
    style=$1 # must be one of: nested (default), compact, compressed, or expanded
    sass_assets=$(get-files sass) || error $sass_assets
    sass --update --force --sourcemap=none --style=$style $sass_assets
}

# ----------------------------------------------------
copy_css(){
    title 'Copy CSS:'
    css_assets=$(get-files css) || error $css_assets
    if cp $css_assets "$distroot/css"; then
        ok $css_assets
    else
        err $css_assets
    fi
    title 'Copy CSS Images:'
    cssimages_assets=$(get-files cssimages) || error $cssimages_assets
    if cp $cssimages_assets "$distroot/css/images"; then
        ok $cssimages_assets
    else
        err $cssimages_assets
    fi
}

# ----------------------------------------------------
copy_images(){
    title 'Copy Images:'
    image_assets=$(get-files images) || error $image_assets
    if cp -r $image_assets "$distroot/images"; then
        ok $image_assets
    else
        err $image_assets
    fi
}

# ----------------------------------------------------
build_html(){
    title 'Build html:'

    destdir=$distroot
    parent_template=$($getdata $config_file files "default parent template")
    html_assets=$(get-files html) || error $html_assets
    build_html=$(get-files app_html) || error $build_html

    template_root=$($getdata $config_file files template_dir)
    app_name=$($getdata $config_file strings 'app name')

    cp $parent_template ./build.html

    for content_html in $html_assets; do
        # sed -i '1s/^/<!-- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -->\n/' $content_html
        if $build_tools_dir/html-builder $content_html . ./build.html \
            --var="build_html::build.html" \
            --var="app_name::$app_name" \
            --var="template_root::$template_root" \
              >$output_file; then
            ok $content_html
        else
            more $output_file
            err 'compile error' $content_html
            exit 1
        fi
    done
    cp build.html $destdir/index.html
}

# ----------------------------------------------------
tidy_html(){
    title 'Tidy html:'

    tidy -indent -modify -asxhtml \
        -wrap 100 -file $output_file $destdir/*html;

    if [ $? == 0 ]; then
        ok 'tidy: $destdir'
    elif [ $? == 1 ]; then
        warn=$(colorize "[some warnings]" $yellowf)
        ok "$warn tidy: $destdir/*html"
    elif [ $? == 2 ]; then
        err 'tidy error' " $destdir/*html"
    fi
}

# ----------------------------------------------------
showtree(){
    if [ "$quiet" == 'quiet' ]; then return; fi
    echo
    tree -h --dirsfirst $distroot
}

case $1 in
    dev)
        dolint
        rebuild_dir
        compile_js 'fastcompile'  # pretty, fast, fastcompile, fake, nil
        compile-or-copy_vendor
        compile_sass
        copy_css
        copy_images
        build_html
        tidy_html

        showtree
        ;;
    fast)
        rebuild_dir
        build_html
        compile_sass 'expanded'
        copy_css
        copy_images
        compile_js 'fast'
        compile-or-copy_vendor

        # showtree
        #cp test.html $distroot

        ;;
    prod)
        echo 'Not implemented yet'
        # compile js handlebar templates
        # set debug flag with @define
        ;;
    compile_vendor)
        echo 'Not implemented yet'
        ;;
    clean)
        echo 'Not implemented yet'
        # delete sqlite db?
        ;;
    lint)
        dolint
        ;;
    fakecompile)
        compile_js fake
        ;;
    verifysource)
        verify
        ;;
    *)
        if [ "$1" ]; then
            echo "Unknown command: $1"
        fi
        echo "Usage: $(basename $0) [dev|prod|fast|compile_vendor|clean|lint|fakecompile|verifysource]"

esac
