#!/usr/bin/env python

'''
HTML Builder

Usage:
  html-builder <filename> <parent> <destination>

All arguments are required.

filename:     Source filename
parent:       Parent template to combine with filename
destination:  Destination for compiled html

'''

import re, sys
from docopt import docopt


def main(args):
    filename = args['<filename>']
    parent = args['<parent>']
    destination = args['<destination>']

    try:
        content = open(filename).read()

        # extract info tags from source file
        mtitle = re.search('<template-title>(.*)</template-title>', content)
        title = mtitle.groups()[0]
        title_tag = mtitle.group()
        # print 'title:', title, title_tag

        mfilename = re.search('<template-filename>(.*)</template-filename>', content)
        filename = mfilename.groups()[0]
        filename_tag = mfilename.group()
        # print 'filename:', filename, filename_tag

        # now erase info tags
        content = content.replace(filename_tag, '')
        content = content.replace(title_tag, '')

        # create compiled html file
        frame_file = parent
        frame = open(frame_file).read()
        full = frame.replace('[title]', title).replace('[content]', content)

        dest = open(destination + '/' + filename, 'w')
        dest.write(full)
        dest.close()

    except AttributeError as e:
        print e
        sys.exit(1)

    sys.exit()


if __name__ == '__main__':

    args = docopt(__doc__, version='0.1')
    main(args)
