#!/usr/bin/env python

'''
HTML Builder

Usage:
  html-builder <filename> <destination> [variables]

filename and destination are required.

variables is an optional json formated string that contains
replacement values for placeholder strings in the html file.  The
placeholder looks like this: %placeholder%

filename:     Source filename
destination:  Destination for compiled html
variables:    JSON formated string

'''

import re, sys
from docopt import docopt


def main(args):
    filename = args['<filename>']
    parent = args['<parent>']
    destination = args['<destination>']
    substitute = args['variables']

    try:
        content = open(filename).read()

        # extract info tags from source file
        mtitle = re.search('<template-title>(.*)</template-title>', content)
        title = mtitle.groups()[0]
        title_tag = mtitle.group()

        mfilename = re.search('<template-filename>(.*)</template-filename>', content)
        filename = mfilename.groups()[0]
        filename_tag = mfilename.group()

        reparent = re.search('<template-parent>(.*)</template-parent>', content)
        parent = reparent.groups()[0]
        parent = parent.replace(substitute['%template_root%'], template_root)
        parent_tag = reparent.group()

        # now erase info tags
        content = content.replace(filename_tag, '')
        content = content.replace(title_tag, '')

        # create compiled html file
        frame_file = parent
        frame = open(frame_file).read()
        full = frame.replace('[title]', title).replace('[content]', content)

        dest = open(destination + '/' + filename, 'w')
        dest.write(full)
        dest.close()

    except AttributeError as e:
        print e
        sys.exit(1)

    sys.exit()


if __name__ == '__main__':

    args = docopt(__doc__, version='0.1')
    main(args)
