#!/usr/bin/env python

'''
Project ini reader

Usage:
  read-data <inifile> <section> <value>
'''

from docopt import docopt
import ConfigParser
import sys, os

def main(args):
    cf = ConfigParser.ConfigParser()
    cf.read(args['<inifile>'])
    value = cf.get(args['<section>'], args['<value>'])
    value = value.strip()

    if value.startswith('~'):
        value = os.path.expanduser(value)

    print value


if __name__ == '__main__':

    args = docopt(__doc__, version='0.1')
    main(args)
