#!/usr/bin/env python

'''
Project ini reader

Usage:
  read-data <inifile> <section> <value>
'''

from docopt import docopt
import ConfigParser
import sys, os

def main(args):
    cf = ConfigParser.ConfigParser()
    cf.read(args['<inifile>'])
    value = cf.get(args['<section>'], args['<value>'])
    value = value.strip()

    # Because the shell does not expand the tilde (~) key for the
    # users home dir when its in a string, we do it here.  If the data
    # does not look like a file, it *probably* will not be changed.
    #
    # One issue, if the path is meant for a non-local filesystem, it
    # will still be expanded using the local user home dir, so to
    # work around that, use a full path for a remote filesystem.
    lines = []
    values = value.split('\n')
    for line in values:
        if line.startswith('~'):
            line = os.path.expanduser(line)
        # normpath defaults to '.' if its an empty string,
        # which we don't want.  So skip normpath if line empty.
        if line: line = os.path.normpath(line)
        lines.append(line)
    value = '\n'.join(lines)

    print value


if __name__ == '__main__':

    args = docopt(__doc__, version='0.1')
    main(args)
