#!/usr/bin/env python

from argparse import ArgumentParser
import ConfigParser


def main(args):
    cf = ConfigParser.ConfigParser()
    cf.read(args.datafile)
    files = cf.get('source files', args.section)

    print files


if __name__ == '__main__':

    parser = ArgumentParser (description='Get filenames from ini file for build script.')

    parser.add_argument(
        'datafile',
        help='Data ini file to read from',
        )
    parser.add_argument(
        'section',
        help='Section in ini file to read',
        )

    parser.add_argument('--version', action='version', version='%(prog)s 0.1')

    args = parser.parse_args()
    main(args)
